### PR TITLE
Make it possible to configure initial database to use in mariadb_config.json

### PR DESCRIPTION
**Pull request by sunxiaoguang**
Make it possible to configure initial database to use in mariadb_config.json

### CODE REVIEW

**Comment by sunxiaoguang** [comment]
Issue: closes #39

**Comment by grooverdan** [comment]
Looks all right to me. Thanks.

**Comment by sunxiaoguang** [comment]
It looks strange that the linter failed due to failing to import a package. I tried to run black locally and didn't get similar error.

**Comment by sunxiaoguang** [comment]
> Looks all right to me. Thanks.

Hello @grooverdan , thanks for replying. Could you please give me some hint about why the test failed. I could reproduce it and it doesn't look like caused by changes in commit. Thanks.

**Comment by grooverdan** [comment]
I couldn't work it out in a brief look when I last looked at it. Will need local testing.

**Comment by LinuxJedi** [comment]
CI was failing due to a bug in the CI. I've rebased against master to fix that.

**Review by LinuxJedi — APPROVED** [review]
Many thanks for the contribution.

**Pull request merged**
